### ISSUE TITLE
Ainda CONGELA o site numa ação específic

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/contatospolis#7]
O site congela quando vou "criar usuário". O site trava inclusive na raiz do Litoral.

Precisamos faze uma analise simples do que pode ser esse problema. Se eh incompatibilidade com algum plugin ou ambiente, precisamos apresentar isso ao cliente.

**Comment by diogosp** [comment]
problema resolvido quando voltou tudo pra versão anterior @LuwkasLima @matheusgimenez
