### ISSUE TITLE
Botoes de acao em cima do resultado da pesquisa nao funcionam

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/contatospolis#8]
Quando faço uma busca simples aparecem os botões de ação em cima dos resultados da pesquisa. Nenhum deles está funcionando:

![image](https://cloud.githubusercontent.com/assets/5949986/12988257/7b2ffbd6-d0c5-11e5-8932-f3206f6c8b74.png)

**Comment by diogosp** [comment]
problema resolvido quando retornamos pra versão anterior. @LuwkasLima @matheusgimenez
