### ISSUE TITLE
Informacao aparecendo no canto direito das paginas

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/contatospolis#9]
Está aparecendo no canto direito em todas as páginas um lance que acho que é do Rolopress original e que havia sido retirado, mas está lá ainda (acho que a atualização fez isto):

![image](https://cloud.githubusercontent.com/assets/5949986/12988300/ae7ce472-d0c5-11e5-9663-d1bd9ea05a6c.png)

**Comment by diogosp** [comment]
problema resolvido quando voltou na versão anterior @LuwkasLima @matheusgimenez
